// Generated by https://quicktype.io
//copiamos la respuesta Json del servidor en la paleta de comandos Ctrl +  Mayús + P pegamos el código en formato JSON y la extensión crea la interfaz correspondiente!!!!!! es una genialidad
export interface User {
  id:    number;
  user:  string;
  email: string;
}
